---
- name: Get ufw Status
  ansible.builtin.systemd:
    name: "ufw"
  register: ufw_status


- name: Disable the ufw firewall (on Ubuntu, if configured).
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  when:
    - ansible_distribution == "Ubuntu"
    - firewall_disable_ufw
    - ufw_status.status.UnitFileState is defined and ufw_status.status.UnitFileState == "enabled"
